### ISSUE TITLE
Turn off background music?

### ISSUE THREAD

**Issue by CJuette** [RobLoach/ChaiLove-Launcher#1]
Hey Rob!

First of all, thanks for this great and simple launcher :) I love to use it to launch other applications from within retroarch using the controller.

Just a small question - is there a way to turn off the background music? I am listening to music in the background most of the time I use the launcher, and the background music is a little bit disturbing then.. 

Also I would love additional customization options (e.g. customizing the background and text color). Maybe if I get time to look at ChaiScript a bit I could also submit a PR, just wanted to let you know of my idea.

Best, Christian

**Comment by RobLoach** [comment]
Glad you checked it out! Great idea... Would be nice to press the B button, and have it mute.

**Comment by RobLoach** [comment]
@Chritzel Made the B button mute the music at the top right.

![main-190118-121244](https://user-images.githubusercontent.com/25086/51407848-03a1f480-1b2b-11e9-9de1-15f5ab9eb320.png)


Would love your thoughts and perhaps test to make sure it's working :+1:

Thanks a lot for the ideas, would love to see it grow.

**Comment by RobLoach** [comment]
Made a release with this and uploaded it to the content downloader. Thanks!
